### ISSUE TITLE
Exception when trying to "save as" - Python 3.5

### ISSUE THREAD

**Issue by MosesofEgypt** [MosesofEgypt/binilla#18]
Can be recreated by opening any tag in binilla and trying to save as. This is probably specific to 3.5, as there is probably a Path object being passed to an os function without being converted to a string.
```python
from binilla import run
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python35\lib\tkinter\__init__.py", line 1558, in __call__
    return self.func(*args)
  File "C:\Python35\lib\site-packages\binilla\app_window.py", line 1367, in save_as
    self.save_tag_as()
  File "C:\Python35\lib\site-packages\binilla\app_window.py", line 1474, in save_tag_as
    initialdir=os.path.dirname(tag.filepath), defaultextension=ext,
  File "C:\Python35\lib\ntpath.py", line 239, in dirname
    return split(p)[0]
  File "C:\Python35\lib\ntpath.py", line 204, in split
    d, p = splitdrive(p)
  File "C:\Python35\lib\ntpath.py", line 139, in splitdrive
    if len(p) >= 2:
TypeError: object of type 'WindowsPath' has no len()
```

**Comment by ShellyHerself** [comment]
Cannot reproduce on Python 3.7.5 - Linux

**Comment by MosesofEgypt** [comment]
It's not tkinter related, it's the line `initialdir=os.path.dirname(tag.filepath)`. tag.filepath is a pathlib.Path object. This is a 3.5 issue.
