### ISSUE TITLE
Setup script should fetch dependencies

### ISSUE THREAD

**Issue by Mimickal** [MosesofEgypt/binilla#25]
This project depends on supyr_struct and threadsafe_tkinter. The readme mentions supyr but not tkinter. We should cut down the amount of toil required installing this by making the setup script do it for us, or add a requirements.txt or something.

**Comment by Mimickal** [comment]
Also, installing threadsafe_tkinter and supyr_struct (without having them installed before) leaves me with this error:
```
python3 -m binilla
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mia/.local/lib/python3.5/site-packages/threadsafe_tkinter/__init__.py", line 35, in <module>
    from tkinter import *
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mia/git/Sigmmma/binilla/binilla/__main__.py", line 17, in main
    from binilla.app_window import Binilla
  File "/home/mia/git/Sigmmma/binilla/binilla/app_window.py", line 7, in <module>
    import threadsafe_tkinter as tk
  File "/home/mia/.local/lib/python3.5/site-packages/threadsafe_tkinter/__init__.py", line 37, in <module>
    from Tkinter import *
ImportError: No module named 'Tkinter'
```

**Comment by ShellyHerself** [comment]
Tkinter needs to be installed on the system level as it explains in the error. We cannot make this part of setup.py because tkinter is not a pypi package but instead part of the Python standard library on Windows and installed as a system package on Linux. You need to apt-get it.
